version: '3.7'

services:
  postgres:
    image: postgres
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: process.env.DATABASE_USERNAME
      POSTGRES_PASSWORD: process.env.DATABASE_PWD
      POSTGRES_DB: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always